### ISSUE TITLE
System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by 0xElessar** [GhostPack/Certify#25]
Running on Win10 21H2 :
`Certify.exe find /vulnerable`

results in the following error message:

````
[!] Unhandled Certify exception:

System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Certify.Commands.Find.IsCertificateTemplateVulnerable(CertificateTemplate template, List`1 currentUserSids)
   at Certify.Commands.Find.<>c__DisplayClass19_0.<ShowVulnerableTemplates>b__0(CertificateTemplate t)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Certify.Commands.Find.ShowVulnerableTemplates(IEnumerable`1 templates, IEnumerable`1 cas, List`1 currentUserSids)
   at Certify.Commands.Find.FindTemplates(Boolean outputJSON)
   at Certify.Commands.Find.Execute(Dictionary`2 arguments)
   at Certify.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Certify.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)
```

**Comment by seahop** [comment]
Big bump to this one. 

https://github.com/GhostPack/Certify/commit/8b898b78abfeb55d84b9f0d3ac652c95f32388d1 this was the break, and specifically "template.ApplicationPolicies". 

When enumerating, it's failing on a <null> value in mspki-certificate-application-policy.

**Comment by DanTheMan-NL** [comment]
I also receive this error while searching for vulnerable templates.
