### ISSUE TITLE
Unhandled Exception by meterpreter/shell. 

### ISSUE THREAD

**Issue by hvprvtr** [GhostPack/Certify#34]
If i run 

`.\Certify.exe find`

from meterpreter (execute -i -f ...) or from meterpreter shell, i got this error.

```
[*] Action: Find certificate templates
[*] Using the search base 'CN=Configuration,DC=essos,DC=local'

[!] Unhandled Certify exception:

System.DirectoryServices.DirectoryServicesCOMException (0x80072020): An operations error occurred.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at Certify.Lib.LdapOperations.GetEnterpriseCAs(String caName)
   at Certify.Commands.Find.FindTemplates(Boolean outputJSON)
   at Certify.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Certify.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)


Certify completed in 00:00:00.0272533

```
It is good then i run by RDP or WinRM, but how to fix this problem? 

GOAD, Microsoft Windows Server 2016 Standard Evaluation

**Comment by hvprvtr** [comment]
cme smb ... -x '.\Certify.exe find' got this trouble too.

**Comment by leechristensen** [comment]
Are you sure your current logon session has credentials? Sounds like you might be executing form a network logon session, and Certify cannot authenticate (a.k.a. the double hop problem)

**Comment by hvprvtr** [comment]
Thanks, it is logon problem.
