### ISSUE TITLE
Unable to cast object of type 'System.DirectoryServices.AccountManagement.GroupPrincipal' to type 'System.DirectoryServices.AccountManagement.UserPrincipal'

### ISSUE THREAD

**Issue by MickeyDB** [GhostPack/Certify#36]
```
.\Certify.exe request /ca:LBABEPW114.REDACTED.com\REDACTED-Enterprise-Root-CA01 /template:REDACTEDCA01 /altname:REDACTEDUSER /domain:REDACTED.com /ldapserver:LBABEPW121.REDACTED.com

   _____          _   _  __
  / ____|        | | (_)/ _|
 | |     ___ _ __| |_ _| |_ _   _
 | |    / _ \ '__| __| |  _| | | |
 | |___|  __/ |  | |_| | | | |_| |
  \_____\___|_|   \__|_|_|  \__, |
                             __/ |
                            |___./
  v1.1.0

[*] Action: Request a Certificates

[*] Current user context    : REDACTEDDOMAIN\REDACTEDUSER

[!] Unhandled Certify exception:

System.InvalidCastException: Unable to cast object of type 'System.DirectoryServices.AccountManagement.GroupPrincipal' to type 'System.DirectoryServices.AccountManagement.UserPrincipal'.
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.UserPrincipal.get_Current()
   at Certify.Cert.GetCurrentUserDN()
   at Certify.Cert.CreateCertRequestMessage(String templateName, Boolean machineContext, String subjectName, String altName, String sidExtension)
   at Certify.Cert.RequestCert(String CA, Boolean machineContext, String templateName, String subject, String altName, String sidExtension, Boolean install)
   at Certify.Commands.Request.Execute(Dictionary 2 arguments)
   at Certify.CommandCollection.ExecuteCommand(String commandName, Dictionary 2 arguments)
   at Certify.Program.MainExecute(String commandName, Dictionary 2 parsedArgs)


Certify completed in 00:00:00.1875661```

I have no idea where this is coming from. I tried with different Certify versions but keep getting this error.

**Comment by ElnurBDa** [comment]
Hi! 
Did you solve it? @MickeyDB
