### ISSUE TITLE
Crash on Windows Server 2016

### ISSUE THREAD

**Issue by BlackyFox** [GhostPack/Certify#6]
Hi, 

I was trying out some requests and an exception is returned during execution.
Compiled on Windows Server 2022 with VS2019.

`.\Certify.exe find /vulnerable` or `.\Certify.exe find /clientauth` works fine.
The error comes when I try the following command: `.\Certify.exe request /ca:REDACTED /template:REDACTED /altname:DOMAIN\REDACTED`

```
[*] Action: Request a Certificates

[!] Unhandled Certify exception:

System.IO.FileNotFoundException: Could not load file or assembly 'Interop.CERTENROLLLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Interop.CERTENROLLLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Certify.Cert.RequestCert(String CA, Boolean machineContext, String templateName, String subject, String altName, Boolean install)
   at Certify.Commands.Request.Execute(Dictionary`2 arguments)
   at Certify.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Certify.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

No cert is returned after the exception.
The script is executed directly on a AD CS, with admin rights.

Edit: This exception also occurs when using the `download` function.

**Comment by leechristensen** [comment]
This should be fixed now with 4c24a835527e5524d5fd2777fc7185422cf5fe4d. If any of you could test and verify, please let us know if it solved your problem!

**Comment by Envincion** [comment]
Same issue ,can someone help how to solve this thing ..?

**Comment by Julienpeps** [comment]
Hey, just ran into the issue, found a quick fix. Just added the following in `packages.config`, hope it helps!
```
<package id="Interop.CERTENROLLLib" version="1.0.0" targetFramework="net40" developmentDependency="true" />
```

**Comment by OlivierLaflamme** [comment]
I somehow still ran into this issue. 

The solution is to use run ILRepack (nuget download) and add Interop.CERTENROLLLib.dll standalone

`C:\Users\X\.nuget\packages\ilrepack\2.0.35\tools\ILRepack.exe standaloneCertipy.exe C:\Mac\Home\Downloads\Certify-main\Certify\bin\Debug\Certify.exe Interop.CERTENROLLLib.dll`

should be good after
